FROM mysql/mysql-server:8.0

ENV MYSQL_DATABASE=practice_backend \
  MYSQL_USER=user \
  MYSQL_PASSWORD=password \
  MYSQL_ROOT_PASSWORD=password \
  TZ=Asia/Tokyo

COPY ./.docker/mysql/my.cnf /etc/my.cnf
RUN chmod 644 /etc/my.cnf
